[tool.poetry]
name = "imucal"
version = "0.1.0"
description = "A Python library to calibrate 6 DOF IMUs"
authors = ["Arne Küderle <arne.kuederle@fau.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.1.3"
numpy = "^1.19.2"
# TODO: Move these to extras
matplotlib = "^3.3.2"
h5py = "^2.10.0"

[tool.poetry.dev-dependencies]
doit = "^0.33.1"
pytest = "^6.1.1"
pytest-cov = "^2.10.1"
coverage = "^5.3"
prospector = "^1.3.0"
black = "^20.8b1"

[tool.black]
line-length = 120
target-version = ['py37']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | docs
    | build
    | dist
    | \.virtual_documents
  )/
)
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
